name: MinecordBridge
version: '${project.version}'
main: org.padrewin.minecordbridge.MinecordBridge
api-version: '1.20'
authors: [padrewin]

commands:
  minecord:
    description: MinecordBridge Command
    usage: /minecord (command) [arg1] [arg2]...
    permission: minecord.main
    permission-message: You don't have permission to do that!

permissions:
  minecord.*:
    description: Full access to MinecordBridge plugin.
    children:
      minecord.reload: true
      minecord.update: true
      minecord.command.reload: true
      minecord.command.retrolink: true
  minecord.command.reload:
    description: Can reload the plugin.
    default: op
  minecord.update:
    description: Check for updates.
    default: op
  minecord.command.retrolink:
    description: Send retroactive message to all users that have the roles mentioned in the config.yml file.
    default: op