name: MinecordBridge
version: '${project.version}'
main: org.padrewin.minecordbridge.MinecordBridge
api-version: '1.20'
authors: [padrewin]
commands:
  minecord:
    description: MinecordBridge total permissions
    permission: minecord.admin
    aliases: [mcb, mcord]